### ISSUE TITLE
Missing values  from file set adapter to datalake 

### ISSUE THREAD

**Issue by flomickl** [apache/streampipes#1269]
### Body

Hi 

The file set adapter is losing some entries in the datalake
(starts with 4 entries, but only 2 are saved in the datalake)
Is something wrong with this csv? I don't think so.

## How to reproduce:
1) Setup of adapter with this csv as file set and csv import (delimiter , and header)
[distance.csv](https://github.com/apache/streampipes/files/10714833/distance.csv)

2) create simple pipeline with adapter and directly connected to datalake
does not matter if there are processors involved!

## What happens:
In the datalake are only 2 values stores => ID 2 and 3 are missing 
Only ID 1 and 4 are stored

## What is expected 
all four values are stored in the datalake

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by bossenti** [comment]
I could reproduce the issue, albeit I received 3 out of four records 😅 
Export of data lake is attached
[2023-02-12_test-reproduce_all.csv](https://github.com/apache/streampipes/files/10716778/2023-02-12_test-reproduce_all.csv)

**Comment by tenthe** [comment]
Hello @flomickl,
the problem with the CSV file is that it has no column for the "timestamp".
When you replay the data, the data is streamed as fast as it can be read. This means that all events are be created and a timestamp will be appended in the adapter.
It is very likely that multiple events will have the same timestamp and since this is the index in the data lake, only one of these events will be stored.

One possible solution would be to add a timestamp to the raw events. Another solution is to mark one of the properties as a dimension property, since one event can be stored for each dimension even if it has the same timestamp.

I hope this is helpful.
Thanks a lot!
Philipp
