### ISSUE TITLE
Notification counter is not reset

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1533]
### Apache StreamPipes version

dev (current development state)

### Affected StreamPipes components

Backend, UI

### What happened?

When deleting a pipeline that sends notifications, the messages are no longer available in the notifications overview.
However, the number of unread notifications remains and is not reset.

![notification-counter](https://user-images.githubusercontent.com/50115603/235316111-ec5b9caf-1e5f-4491-838b-6b6671c14451.gif)

### How to reproduce?

see above

### Expected behavior

From my point of view there are two alternatives:

a) the notification counter is reset as well
b) the notifications are not deleted automatically when removing the associated pipeline

### Are you willing to submit a PR?

None

**Comment by dominikriemer** [comment]
Hi @bossenti 
Currently, notifications are bound to a pipeline so that notifications are not shown if a pipeline is no longer present. I would see two options to solve this:
1) Notifications that belong to a pipeline are deleted once the pipeline is deleted.
2) We rewrite the notification module so that notifications are not bound to a pipeline, but could potentially also be created by other parts of the application. Notifications in the notification view would then not be organized by pipelines, but would include all notifications assigned to the user and maybe could be filtered by a notification type.

Since I think existing notification should not just disappear as in option 1, I tend to prefer 2. What do you think?

**Comment by bossenti** [comment]
I agree with you that option 2 is the way to go hear.
But with the current implementation it is not possible to see/access the notifications once the pipeline is deleted right?
So until option 2 is implemented, option 1 might be good short-term solution? 🤔
