### ISSUE TITLE
New Processor: Round Numeric Values

### ISSUE THREAD

**Issue by tenthe** [apache/streampipes#1688]
### Description
A user should have the ability round numeric values in a pipeline. Therefore, a new processor is required that provides the functionality to round numeric numbers of the event.

### Example Configuration
- **Multiselect**: The processor should allow the user to select all numeric values in the data stream for rounding.
- **Numeric Input**: The user should be able to specify the precision to which the values should be rounded.

### Output Schema
The input schema should not be changed

### Additional Functionality
If you have any other ideas for the functionality of this new processor, please feel free to add them here.

### Mentoring
As this issue is marked as good first issue: one of @dominikriemer, @tenthe, or @bossenti are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.
This issue is ideal for people that are interested in getting started with StreamPipes and its SDK.

### StreamPipes Committer

I acknowledge that I am a maintainer/committer of the Apache StreamPipes project.

**Comment by muyangye** [comment]
Hi, I have been using Streampipes for a while and I absolutely love the project. Since no one has taken this issue yet I can try. Any suggestions to get started? Like is there a guide to create a new processor and should this round processor be under math or filter or transformation? Thanks!

**Comment by bossenti** [comment]
Thanks a lot for your nice words @muyangye!
We would really appreciate a contribution here.

You can find a tutorial on implementing processing elements here: https://streampipes.apache.org/docs/extend-tutorial-data-processors
I would simply assign this element to the math transformation elements

Feel free to reach out, whenever you face any issue. We are happy to guide you 🙂

**Comment by muyangye** [comment]
I have finished the implementation and tested locally using a FileStream source, should I submit a PR now (sorry if this is a dumb question, this is my first time contributing to OSS)? That being said, I still have 4 questions (and my current approach):

- I am using Labels.from() to create a label and according to source code this method is marked as deprecated. Is this a problem?
- Just want to confirm the exact meaning of rounding, currently I am using the conventional round half up.
- When I try to update the new processor, there's an error message "Icon missing", is there a place to add an icon to the processor?
- This question is not really related to this processor but I am curious: Why only event.addField()'s implementation uses runtime name (what's after s0::) and other functions such as getFieldBySelector() and removeFieldBySelector() use the selector?

Cheers,
Muyang

**Comment by dominikriemer** [comment]
Hi @muyangye and thanks for the PR!
Here are some answers to your questions:
* Instead of Labels.from, you can use `Labels.withId` by providing an ID only. By doing so, you can provide a `strings.en` file in the resources folder where you can provide titles and descriptions for every ID that you refer to. The advantage is that this approach allows us to add more translations in the future, once a multi-language StreamPipes version is available. There are many examples in the `streampipes-extensions` folder, e.g., `streampipes-processors-filters-jvm` that might help to see how IDs can be provided.
* I think conventional rounding is ok, or we could think of an advanced version where the user could provide the number of digits to round to.
* The icon can also be placed in the resources folder similar to the `strings.en` file. In addition, a markdown file with a documentation of these elements can be placed here. I hope the examples in the extensions folder are helpful (the `appId` of the pipeline element must match the folder name in the resources folder.
* The reason why we use a prefix here is that a pipeline element can have more than one input stream, where both streams provide fields with the same name. To uniquely identify a field, we use the selector. Since there is only one output stream, this is not needed when adding a new field to the event. You could also use the `updateFieldBySelector` method to update the field, and I think there is also a method like `getFieldNameOut` which should return the field name without selector.

Hope this helps! Please feel free to ask in case I did not properly answer your questions. Thanks again for your contribution!

**Comment by dominikriemer** [comment]
One addition, when you change the pipeline element description in your code and would like to check the result in the UI, do not forget to go to `Install Pipeline Elements`, and click on `Update` (in the menu when clicking the three dots of the pipeline element) to make sure the description is properly updated. :-)

**Comment by muyangye** [comment]
Hi @dominikriemer, thanks for the detailed answers! These are exactly what I asked for. I have pushed an update that follows the new procedure to create new processors. By the way I found the icon online so I'm not sure if there's a copyright issue :)
