### ISSUE TITLE
Implement unit tests for pipeline element 'BooleanFilterProcessor'

### ISSUE THREAD

**Issue by bossenti** [apache/streampipes#1891]
This issue is about implementing unit tests for our pipeline element [BooleanFilterProcessor](https://github.com/apache/streampipes/blob/752289c6acfc8fa10398c920d678c5c02143ed5c/streampipes-extensions/streampipes-processors-filters-jvm/src/main/java/org/apache/streampipes/processors/filters/jvm/processor/booleanfilter).
An example of how to write unit tests for pipeline elements can be found [here](https://github.com/apache/streampipes/tree/ca4e0c2d44c1a713caaee3e9c1bff46096f41c53/streampipes-extensions/streampipes-processors-transformation-jvm/src/test/java/org/apache/streampipes/processors/transformation/jvm/processor).

### Mentoring
As this issue is marked as a good first issue and for the `hacktoberfest` event: one of @dominikriemer, @tenthe, @RobertIndie, or @bossenti are happy to provide help for getting started, just tag (one of) them if you want to start working on this issue and need some help.

**Comment by muyangye** [comment]
Can someone please assign this issue to me? I know I am not a first time contributor but I have never worked on unit test before. I believe this will give me a more well-rounded understanding of the project. Thanks!

**Comment by bossenti** [comment]
Awesome, @muyangye!
`good first issues` are not intended to be exclusive for first-time contributors but are especially appropriate 🙂 
So feel always free to catch them

**Comment by muyangye** [comment]
Hi I have pushed a PR that unit tests BooleanFilterProcessor. 2 quick concerns I have:

- Does the directory structure seem good? Since no one has written any unit tests for module `streampipes-processors-filters-jvm` yet, I followed the directory structure convention of module `streampipes-processors-transformation-jvm` and created some new packages. I am not sure so please let me know the correct directory structure.
- In order to test all filter processors, one needs to be able to tell the number of events being filtered. However, because SpOutputCollector is just an interface, one must define a class that implements the interface so that he can get the number of events. I followed the class in [this test](https://github.com/apache/streampipes/blob/ca4e0c2d44c1a713caaee3e9c1bff46096f41c53/streampipes-extensions/streampipes-processors-transformation-jvm/src/test/java/org/apache/streampipes/processors/transformation/jvm/processor/value/change/TestChangedValueDetectionProcessor.java) and I think other developers implementing unit tests for filter processors will probably do the same. Do you think it's a good idea to extract this class to make it commonly usable?

**Comment by bossenti** [comment]
Thanks for your contribution @muyangye 

> I am not sure so please let me know the correct directory structure.

The structure you have created is totally fine and exactly what I would have expected

> Do you think it's a good idea to extract this class to make it commonly usable?

Yes, this would be great! How about putting it into `streampipes-test-utils` creating a package called `org.apache.streampipes.test.extensions.api`? (cc @dominikriemer)

**Comment by muyangye** [comment]
Thanks for the suggestion @bossenti! I just pushed an update that:

- Created the new package
- Refactored `TestChangedValueDetectionProcessor`
