### ISSUE TITLE
Add image to documentation.md

### ISSUE THREAD

**Issue by nicolasperivolaris** [apache/streampipes#3198]
### Apache StreamPipes version

dev (current development state)

### Affected StreamPipes components

UI

### What happened?

It seams impossible to display image from the documentation.md file. 

![image](https://github.com/user-attachments/assets/df9ab0b3-c36b-4122-92f4-70fd16ed99b7)

### How to reproduce?

Create a pipeline and add a Geo Buffer Point processor.
Open the documentation for this processor.
The bottom output picture doesn't show up.

### Expected behavior

Image should be displayable in the documentation

### Are you willing to submit a PR?

None

**Comment by dominikriemer** [comment]
@nicolasperivolaris thanks for reporting this.
Some thoughts so that others can follow:
This is due to a 401 error since no auth headers are sent in the image request and it's not easily doable from the markdown file to include the header. I think it's ok to serve all `*.png` files that are included in the pipeline element asset without authentication. But this should be restricted to PNG files only.
