### ISSUE TITLE
1-class processor model and stylechecks on all processors.geo.jvm

### ISSUE THREAD

**Issue by dominikriemer** [apache/streampipes#777]
Started with setEPSG Processor
and validate result

check GeoJvmInit

Imported from Jira [STREAMPIPES-642](https://issues.apache.org/jira/browse/STREAMPIPES-642). Original Jira may contain additional context.
Reported by: micklich.
Subtask of issue #775

**Comment by tenthe** [comment]
Hi @flomickl,
was there a specific reason why you changed the method API of `Event.addField(String runtimeName, Float value)` to `Event.addField(String runtimeName, double value)`?
The nightly e2e tests failed for the `BooleanCounter` processor, because the datatype of the counter (an integer) was changed to a double. I changed the API back to `Float` but wanted to make sure that this does not break any of the other changes you made in the PR.
Cheers,
Philipp

See [1] for my changes and [2] for the e2e test results.
[1] https://github.com/apache/streampipes/commit/7dfe113dc6b30cf20513a4bf69199c50e03bfe79
[2] https://cloud.cypress.io/projects/q1jdu2/runs/401/specs

**Comment by flomickl** [comment]
@tenthe 
Hm I did not touch this file at all, not on purpose. 
I don't know why this file was changed at all in my commit.
Sorry for the inconvenience! Did you revert my "change"?

**Comment by tenthe** [comment]
Hi @flomickl, no problem at all. 
I changed it back, I just wanted to make sure I didn't break anything in the code you wrote.

**Comment by flomickl** [comment]
I stashed all commits before, So I cannot figure it out how it happens and when.
So, I think this ticket can be closed now?
